"""grains_app.py / grains.toml template bodies rendered by `grains init`."""
from __future__ import annotations

_ECHO_APP = '''"""Grains wrapper -- generated by `grains init`."""
from grains import Task


def handle(task: Task):
    return task.reply("echo: " + task.text)
'''

_CREWAI_APP = '''"""Grains wrapper -- generated by `grains init`."""
from grains import Task

# TODO: point this at your crew object, e.g. from my_project.crew import your_crew
from your_project.crew import your_crew  # noqa: F401


def handle(task: Task):
    result = your_crew.kickoff(inputs={"prompt": task.text})
    return task.reply(str(result))
'''

_INVOKE_APP = '''"""Grains wrapper -- generated by `grains init`."""
from grains import Task

# TODO: point this at your chain/graph, e.g. from my_project.graph import your_graph
from your_project.graph import your_graph  # noqa: F401


def handle(task: Task):
    result = your_graph.invoke({"input": task.text})
    return task.reply(str(result))
'''

_NODE_APP = '''// Grains wrapper -- generated by `grains init`.
export function handle(task) {
  return task.reply("echo: " + task.text);
}
'''

_APP_TEMPLATES = {
    "crewai": _CREWAI_APP,
    "langchain": _INVOKE_APP,
    "langgraph": _INVOKE_APP,
    "none": _ECHO_APP,
    "node": _NODE_APP,
}

_RUNTIME_BY_FRAMEWORK = {
    "node": "nodejs20.x",
}
_DEFAULT_RUNTIME = "python3.12"


def render_app(framework: str) -> str:
    return _APP_TEMPLATES.get(framework, _ECHO_APP)


def render_toml(name: str, framework: str = "none") -> str:
    runtime = _RUNTIME_BY_FRAMEWORK.get(framework, _DEFAULT_RUNTIME)
    return (
        "[agent]\n"
        f'name = "{name}"\n'
        'entrypoint = "grains_app:handle"\n'
        f'runtime = "{runtime}"\n'
        "public = false\n"
        "\n"
        "[secrets]\n"
        "names = []\n"
        "\n"
        "# Reserved, not yet enforced: agent outbound traffic is currently\n"
        "# unrestricted. Declaring hosts here changes nothing today -- it is\n"
        "# scaffolding for the egress allowlist (see docs/EGRESS.md). Do not\n"
        "# treat an empty list as a deny-all.\n"
        "[egress]\n"
        "allow = []\n"
    )
